name: ${project.name}
version: ${project.version}
main: com.wyvencraft.WyvenLaunchPads
api-version: '1.21'
author: WyvenCraft
commands:
  launchpad:
    description: Create and manage launchpads
    usage: /<command> <create|link> <name>