name: Build and Release WyvenLaunchPads

on:
  release:
    types: [ published ]

jobs:
  build-and-upload:
    runs-on: ubuntu-latest

    permissions:
      contents: write  # Required to upload release assets

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 23
        uses: actions/setup-java@v4
        with:
          java-version: '23'
          distribution: 'temurin'
          cache: maven

      - name: Build with Maven
        run: mvn clean compile package -DskipTests

      - name: Get project version
        id: version
        run: |
          VERSION=$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout)
          NAME=$(mvn help:evaluate -Dexpression=project.name -q -DforceStdout)
          echo "version=$VERSION" >> $GITHUB_OUTPUT
          echo "jar_name=$NAME-$VERSION.jar" >> $GITHUB_OUTPUT

      - name: Verify JAR exists
        run: |
          if [ ! -f "target/${{ steps.version.outputs.jar_name }}" ]; then
            echo "JAR file not found at target/${{ steps.version.outputs.jar_name }}"
            ls -la target/
            exit 1
          fi

      - name: Upload JAR to Release
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: target/${{ steps.version.outputs.jar_name }}
          asset_name: ${{ steps.version.outputs.jar_name }}
          asset_content_type: application/java-archive